Copyright (c) 2020 ARS Computer & Consulting GmbH

This program and the accompanying materials are made
available under the terms of the Eclipse Public License 2.0
which is available at https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0

In [1]:
import utils
import photo_managing
import model_managing
import notification

In [2]:
pm = photo_managing.PhotoManager("127.0.0.1", 5000)

In [3]:
pm.getPluginList(table_view = True)

,id,name,manufacturer,version,description,price description
0,edu.hm.hsieh_mylocalphotoloader_1.0,mylocalphotoloader,edu.hm.hsieh,1.0,This is a basic photo loader. This loader comp...,1 database operation per photo read/write. Pri...

In [5]:
uploadResult0 = pm.uploadPhotos("edu.hm.hsieh_mylocalphotoloader_1.0", utils.getPhotoList("../Dataset1_simple/foam"))
uploadResult1 = pm.uploadPhotos("edu.hm.hsieh_mylocalphotoloader_1.0", utils.getPhotoList("../Dataset1_simple/nofoam"))

In [6]:
pm.getPhotoList(table_view = True)

,id,created by,created at,upload-plugin id,extra-info
0,28,webuser0,"Mon, 02 Mar 2020 09:42:24 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
1,27,webuser0,"Mon, 02 Mar 2020 09:42:24 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
2,26,webuser0,"Mon, 02 Mar 2020 09:42:24 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
3,25,webuser0,"Mon, 02 Mar 2020 09:42:24 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
4,24,webuser0,"Mon, 02 Mar 2020 09:42:24 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
5,23,webuser0,"Mon, 02 Mar 2020 09:42:24 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
6,22,webuser0,"Mon, 02 Mar 2020 09:42:24 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
7,21,webuser0,"Mon, 02 Mar 2020 09:42:24 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
8,20,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
9,19,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
10,18,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
11,17,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
12,16,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
13,15,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
14,14,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
15,13,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
16,12,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
17,11,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
18,10,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
19,9,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
20,8,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
21,7,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
22,6,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
23,5,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
24,4,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
25,3,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
26,2,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
27,1,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.
28,0,webuser0,"Mon, 02 Mar 2020 09:42:23 GMT",edu.hm.hsieh_mylocalphotoloader_1.0,No Extra Infomation Available.

In [7]:
dataset0 = uploadResult0.uploaded
dataset1 = uploadResult1.uploaded

In [11]:
#dataset0.getPhotoIDFilenameMap()

In [8]:
mm = model_managing.ModelManager("127.0.0.1", 5000)

In [9]:
mm.getPluginList(table_view = True)

,id,name,manufacturer,version,description,price description
0,edu.hm.hsieh_azureimageclassifier_1.0,azureimageclassifier,edu.hm.hsieh,1.0,This model uses Microsoft Azure Custom Vision ...,Pricing see: https://azure.microsoft.com/en-us...
1,edu.hm.hsieh_localfoameliminationdetector_1.0,localfoameliminationdetector,edu.hm.hsieh,1.0,This is model extracts different features from...,Resource this model needs is only CPU resouces...

In [11]:
model = mm.createNewModel("edu.hm.hsieh_azureimageclassifier_1.0", "azureTest5", "its a test model")

In [12]:
mm.getModelList(table_view = True)

,id,nickname,created at,created by,plugin ID,state,description
0,0,azureTest5,"Mon, 02 Mar 2020 09:42:41 GMT",webuser0,edu.hm.hsieh_azureimageclassifier_1.0,STATE_MODEL_CREATED,its a test model

In [13]:
model.feed_train_data(dataset0, 0)
model.feed_train_data(dataset1, 1)

'OK'

In [14]:
model.getID()

0

In [15]:
model.train()

INFO Server answered training model result=200
INFO Training starting:
Trainer fetching model settings.
Training starting...
Retrieving model...
Downloading/Caching and Analyzing training data...
(1/0/29)
(2/0/29)
(3/0/29)
(4/0/29)
(5/0/29)
(6/0/29)
(7/0/29)
(8/0/29)
(9/0/29)
(10/0/29)
(11/0/29)
(12/0/29)
(13/0/29)
(14/0/29)
(15/0/29)
(16/0/29)
(17/0/29)
(18/0/29)
(19/0/29)
(20/0/29)
(21/0/29)
(22/0/29)
(23/0/29)
(24/0/29)
(25/0/29)
(26/0/29)
(27/0/29)
(28/0/29)
(29/0/29)
Training model with 29 photos...
Training status: Training
Training status: Training
Training status: Training
Training status: Training
Training status: Training
Training status: Training
Training status: Training
Training status: Training
Training status: Training
Training status: Completed
Training done.
Done! Model successfully trained and saved.

In [16]:
uploadPredict = pm.uploadPhotos("edu.hm.hsieh_mylocalphotoloader_1.0", utils.getPhotoList("../Dataset1_simple/foam"))
datasetPredict = uploadPredict.uploaded
model.predictWithPhotoList(datasetPredict, view=model_managing.PREDICTION_VIEW_TABLE)

    id class   score
0   29     0  99.98%
1   30     0  99.97%
2   31     0  99.92%
3   32     0  99.07%
4   33     0   99.4%
5   34     0  99.99%
6   35     0  99.99%
7   36     0  99.99%
8   37     0  99.99%
9   38     0  99.99%
10  39     0  99.65%
11  40     0  98.42%
12  41     0  97.12%
13  42     0  98.51%
14  43     0  76.27%
15  44     0  90.22%
16  45     1  68.29%
17  46     1  55.02%

In [17]:
uploadPredict = pm.uploadPhotos("edu.hm.hsieh_mylocalphotoloader_1.0", utils.getPhotoList("../Dataset1_simple/nofoam"))
datasetPredict = uploadPredict.uploaded
model.predictWithPhotoList(datasetPredict, view=model_managing.PREDICTION_VIEW_TABLE)

    id class   score
0   47     1  67.89%
1   48     1   99.3%
2   49     1  99.93%
3   50     1  99.96%
4   51     1  99.93%
5   52     1  99.98%
6   53     1  99.98%
7   54     1  99.99%
8   55     1  99.99%
9   56     1  99.99%
10  57     1  99.99%

In [20]:
model.predictWithPhotos(utils.getPhotoList("../datasets/Ice1/ice"), view=model_managing.PREDICTION_VIEW_TABLE)
#model.predictWithPhotos(utils.getPhotoList("../datasets/Ice1/ice"), view=model_managing.PREDICTION_VIEW_PHOTO)

                              id class  score
0   ../datasets/Ice1/ice\349.bmp     1   0.7%
1   ../datasets/Ice1/ice\350.bmp     1  1.87%
2   ../datasets/Ice1/ice\351.bmp     1  1.93%
3   ../datasets/Ice1/ice\352.bmp     1  0.97%
4   ../datasets/Ice1/ice\353.bmp     1  0.66%
5   ../datasets/Ice1/ice\354.bmp     1  1.22%
6   ../datasets/Ice1/ice\355.bmp     1  0.67%
7   ../datasets/Ice1/ice\357.bmp     1  0.33%
8   ../datasets/Ice1/ice\358.bmp     1  0.38%
9   ../datasets/Ice1/ice\359.bmp     1  1.15%
10  ../datasets/Ice1/ice\360.bmp     1   0.3%
11  ../datasets/Ice1/ice\361.bmp     1  0.48%
12  ../datasets/Ice1/ice\362.bmp     1  0.57%
13  ../datasets/Ice1/ice\363.bmp     1  0.19%
14  ../datasets/Ice1/ice\364.bmp     1  0.12%
15  ../datasets/Ice1/ice\366.bmp     1  0.11%
16  ../datasets/Ice1/ice\367.bmp     1  0.07%
17  ../datasets/Ice1/ice\368.bmp     1  0.19%
18  ../datasets/Ice1/ice\369.bmp     1  0.09%
19  ../datasets/Ice1/ice\370.bmp     1  0.17%
20  ../datasets/Ice1/ice\371.bmp     1  0.08%
21  ../datasets/Ice1/ice\372.bmp     1  0.15%
22  ../datasets/Ice1/ice\373.bmp     1  0.25%
23  ../datasets/Ice1/ice\374.bmp     1  0.53%
24  ../datasets/Ice1/ice\375.bmp     1  0.24%
25  ../datasets/Ice1/ice\376.bmp     1  0.22%
26  ../datasets/Ice1/ice\377.bmp     1  0.39%
27  ../datasets/Ice1/ice\378.bmp     1  4.24%
28  ../datasets/Ice1/ice\379.bmp     1  1.23%
29  ../datasets/Ice1/ice\380.bmp     1  0.88%
30  ../datasets/Ice1/ice\381.bmp     1  0.69%
31  ../datasets/Ice1/ice\382.bmp     1  1.64%

In [19]:
model.predictWithPhotos(utils.getPhotoList("../datasets/Ice1/noice"), view=model_managing.PREDICTION_VIEW_TABLE)

                                  id class  score
0     ../datasets/Ice1/noice\383.bmp     1  0.04%
1     ../datasets/Ice1/noice\384.bmp     1  0.14%
2     ../datasets/Ice1/noice\385.bmp     1  0.04%
3     ../datasets/Ice1/noice\386.bmp     1  0.04%
4   ../datasets/Ice1/noice\388-d.bmp     1  0.03%
5     ../datasets/Ice1/noice\389.bmp     1  0.03%
6     ../datasets/Ice1/noice\390.bmp     1  0.03%
7     ../datasets/Ice1/noice\391.bmp     1  0.03%
8     ../datasets/Ice1/noice\392.bmp     1  0.03%
9     ../datasets/Ice1/noice\393.bmp     1  0.02%
10    ../datasets/Ice1/noice\394.bmp     1  0.02%
11    ../datasets/Ice1/noice\395.bmp     1  0.02%
12    ../datasets/Ice1/noice\396.bmp     0  0.04%
13    ../datasets/Ice1/noice\397.bmp     0  0.03%
14    ../datasets/Ice1/noice\398.bmp     1  0.03%
15    ../datasets/Ice1/noice\399.bmp     1  0.02%
16    ../datasets/Ice1/noice\400.bmp     1  0.04%
17    ../datasets/Ice1/noice\401.bmp     1  0.02%
18    ../datasets/Ice1/noice\402.bmp     1  0.04%
19    ../datasets/Ice1/noice\403.bmp     1  0.02%
20    ../datasets/Ice1/noice\404.bmp     1  0.01%
21    ../datasets/Ice1/noice\405.bmp     0  0.04%
22    ../datasets/Ice1/noice\407.bmp     1  0.04%
23    ../datasets/Ice1/noice\408.bmp     1  0.03%
24    ../datasets/Ice1/noice\409.bmp     1  0.04%
25    ../datasets/Ice1/noice\410.bmp     1  0.04%
26    ../datasets/Ice1/noice\411.bmp     0  0.03%
27    ../datasets/Ice1/noice\412.bmp     0  0.03%
28    ../datasets/Ice1/noice\413.bmp     1  0.04%
29    ../datasets/Ice1/noice\414.bmp     1  0.05%
30    ../datasets/Ice1/noice\415.bmp     0  0.04%
31    ../datasets/Ice1/noice\416.bmp     0  0.04%
32    ../datasets/Ice1/noice\417.bmp     0  0.04%
33    ../datasets/Ice1/noice\418.bmp     0  0.05%
34    ../datasets/Ice1/noice\419.bmp     0  0.03%

In [21]:
utils.getDirectShowDevices("../video_capturer/ffmpeg/bin/ffmpeg.exe")

[dshow @ 00000203c3d59840] DirectShow video devices (some may be both video and audio devices)
[dshow @ 00000203c3d59840]  "Lenovo EasyCamera"
[dshow @ 00000203c3d59840]     Alternative name "@device_pnp_\\?\usb#vid_05e3&pid_0510&mi_00#9&ab0188f&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global"
[dshow @ 00000203c3d59840] DirectShow audio devices
[dshow @ 00000203c3d59840]  "Microphone (JBL Reflect Aware Audio Interface)"
[dshow @ 00000203c3d59840]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{EA69D82F-2E1C-4D2E-A007-2415D599F72E}"

In [22]:
mm = model_managing.ModelManager("127.0.0.1", 5000)
debugModel = mm.modelFactory(17)

In [ ]:
notificater = notification.MQTTNotification("broker.hivemq.com" , 1883, "roger", "password", "KenMLClient", "ken/bachlorarbeit")
with notificater:
    debugModel.streamPredict("../video_capturer/ffmpeg/bin/ffmpeg.exe", 60, 120, "Lenovo EasyCamera", 1, notificater
                             , messageType=notification.MESSAGE_TYPE_TEXT)

DEBUG MQTT LOG:  Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'KenMLClient'
DEBUG MQTT LOG:  Received CONNACK (0, 0)
DEBUG Connected to MQTT-Broker
DEBUG A Photo was succesfully taken at 2020-02-27 09:04:36.143345
>>>>>>>>>>>>>>>>>>> Text Message at 2020-02-27 09:04:36.191197 : Target class '1' detected!
DEBUG MQTT LOG:  Sending PUBLISH (d0, q2, r0, m1), 'b'ken/bachlorarbeit'', ... (26 bytes)
DEBUG MQTT LOG:  Received PUBREC (Mid: 1)
DEBUG MQTT LOG:  Sending PUBREL (Mid: 1)
DEBUG MQTT LOG:  Received PUBCOMP (Mid: 1)